[workspace]
resolver = "3"
members = ["capsolver", "capmonster"]

[workspace.dependencies]
client = { git = "https://github.com/Haikalbugis/client.git" }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
anyhow = "1.0.100"
