[package]
name = "capsolver"
version = "0.1.0"
edition = "2024"

[dependencies]
client = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
